### ISSUE TITLE
cannot get past the user creation screen during installation

### ISSUE THREAD

**Issue by EpicTMC** [Nitrux/nitrux-bug-tracker#162] opened 2024-02-16 09:58 UTC
I cannot get past the user creation screen during installation.

Steps taken to create issue:
- Downloaded iso from Sourceforge via Nitrux website
- Wrote iso to usb
- Booted from usb on Dell latitude laptop
- Nitrux desktop loads, i add device to wifi* 
- Click install shortcut, and installer window loads
- Go through initial location and keyboard layout screens
- Arrive at problematic user creation screen:

User name: First and Last name (upper and lower characters)
Device name: 1 word (lower case characters and number)
User password: >8 characters, upper, lower, number, special characters
Root password: >8 characters, upper, lower, number, special characters
NOTE: i used password generator to create complex password
I also tried combo of ticking and unticking all options at the bottom for password complexity and auto login

The issue is whatever is typed or selected the 'NEXT' button remains greyed out. 
I cannot get past this screen to install the OS on my laptop.

*Separate note when i first loaded the installer window it told me that i was not on wifi, when i connected to wifi the installer did not recognise i was connected, i closed the installer window and reopened it and it said the same thing. i looked in wifi settings and could see it was connected. So i reconnected as WPA3-Personal and loaded the installer screen and it worked from there on -  this may be problematic for non-technical users.

**Comment by UriHerrera** [comment] 2024-02-19 00:36
With the information you gave me, it's impossible to reproduce the problem. The bug report template lists all the necessary information to troubleshoot problems correctly.

Please provide the necessary information listed in the template.

**Comment by UriHerrera** [comment] 2024-02-26 21:25
With the information you gave me, it's impossible to reproduce the problem. The bug report template lists all the necessary information to troubleshoot problems correctly.

Please provide the necessary information listed in the template.

----

As explained before, there's no indication of where the problem could be without further information. While it doesn't seem a duplicate of #45 (because it seems like the problem was for different reasons), my only guess is that the target storage device uses MBR; thus, there's no room for another primary partition or enough storage space to create the partition layout.

The [tutorial to install the distribution](https://nxos.org/tutorial/how-to-install-nitrux/#installing-nitrux) explicitly mentions the following.

> ⚠️ Important: We strongly discourage using an [MBR (Master Boot Record)](https://en.wikipedia.org/wiki/Master_boot_record) storage device when installing Nitrux due to the limitations of this type of partition table, i.e., MBR has a limit of four primary partitions. We strongly suggest using a different storage device to install Nitrux that does not use MBR or deleting the partition table and using [GPT (GUID Partition Table)](https://en.wikipedia.org/wiki/GUID_Partition_Table) instead. Alternatively, [visit this link at AskUbuntu to learn how to convert the partition table from MBR to GPT without data loss.](https://askubuntu.com/questions/1314111/convert-mbr-partition-to-gpt-without-data-loss).

Either way, I can't know without any detailed information.

**Closed** 2024-04-16 17:44 UTC
Labels: unreproducible, missing-info, user-support
