### ISSUE TITLE
Support for Teclast F5

### ISSUE THREAD

**Issue by hal1200** [Nitrux/nitrux-bug-tracker#1] opened 2018-12-04 10:16 UTC
Not sure if this is really a problem
No WiFi or touchscreen 
But also doesn't work on other distros
Rumor that this laptop (manufactured in Korea, has other variants) works on Antergos
Will try to investigate by seeing if this rumor is true. If it isn't I may close this issue

**Comment by UriHerrera** [comment] 2019-07-02 00:13
To troubleshoot hardware support, we require to have the hardware. We don't possess one currently, so I'll close this and reopen it when possible.

**Closed by UriHerrera** 2019-07-02 00:13 UTC
Labels: feature-request

**Comment by ijonglin** [comment] 2020-06-19 16:05
If you're curious, I can confirm that this laptop works on Ubuntu 20.04 with some modifications.  If Nitrux is ubuntu-based, then it should work, but sleep may fail to due touchpad problems w/o modifications as described in https://github.com/ijonglin/teclast-f5-ubuntu-finalizer.
