### ISSUE TITLE
Live ISO with Plasma Desktop requires manual login (does not autologin to desktop) 

### ISSUE THREAD

**Issue by joevaughan** [Nitrux/nitrux-bug-tracker#119] opened 2023-07-01 08:17 UTC
**Describe the bug**

Boot the live (KDE Plasma) ISO for the official 2.9.0 release as linked from here: https://nxos.org/get/latest/?tmstv=1688067999

When the system boots the user is greeted by a login screen saying "Welcome back" - screenshot below

![image](https://github.com/Nitrux/nitrux-bug-tracker/assets/92576588/ec07d5a4-0005-4dfc-9356-34e77493757b)

Note: The Maui-shell ISO does not have this issue and boots to a live desktop as expected.

**Comment by N0rbert** [comment] 2023-07-01 09:43
Confirmed with nitrux-nx-desktop-plasma-ce3e8fa9-amd64.iso.
Here login _nitrux_ and password _nitrux_ are accepted. 
But this is not user-friendly at all. Please configure auto-login in the live medium.

**Comment by UriHerrera** [comment] 2023-07-01 11:17
[As with Calamares](![imagen](https://github.com/Nitrux/nitrux-bug-tracker/assets/3053525/67140cbb-bfb2-4fcc-947e-813e0f8537db)), this is an issue with casper+SDDM+Wayland. Both autologin to Plasma X11 but not to Plasma Wayland.

**Comment by UriHerrera** [comment] 2023-07-20 20:46
As I just noted in the previous comment and #105, the issue is that casper and Calamares expect the graphical session to be an X11 session; in the case of Plasma, both seem to expect specifically that the session is `/usr/share/xsessions/plasma.desktop`. 

As far as we're concerned, this is a bug in casper and Calamares.

**Comment by UriHerrera** [comment] 2023-08-15 21:26
Below is the moment where Calamares __fails__ to enable autologin. As I noted before, it expects the session to the specifically `plasma`, and that is the name of the X11 session. This is indeed a Calamares problem.

```
2023-08-15 - 20:50:23 [6]:     .. Job description from __doc__ "displaymanager" = "Configure display managers." 
2023-08-15 - 20:50:23 [2]: WARNING: [PYTHON JOB]: "The configured default desktop environment, plasma, can not be found." 
2023-08-15 - 20:50:23 [2]: boost::python::api::object CalamaresPython::GlobalStoragePythonWrapper::value(const string&) const
    WARNING: Unknown GS key autoLoginUser 
2023-08-15 - 20:50:23 [6]: [PYTHON JOB]: "Unsetting autologin." 
```

**Comment by UriHerrera** [comment] 2023-08-16 01:22
As I just noted in the previous comment and [#105](https://github.com/Nitrux/nitrux-bug-tracker/issues/105), the issue is that casper expects that the session is `/usr/share/xsessions/plasma.desktop` hence why the autologin feature does not work for the Live user.

As far as we're concerned, this is a bug in casper. I'll keep the issues on our bug tracker open for others to know about this problem; however, ***this is not a bug, issue, or problem caused by Nitrux, nor is it a misconfiguration in the distribution***.

---

_Disclaimer_: We do not develop casper. Please create issues at its bug tracker [here](https://bugs.launchpad.net/ubuntu/+source/casper) to request features or report problems.

**Comment by UriHerrera** [comment] 2023-08-18 18:06
As I figured, here's the truncated content of one of the scripts in casper that deals with autologin for the Live sessions `15autologin`. And indeed, casper expects the Plasma session to be `plasma` and not `plasmawayland`. At least now we know why the problem occurs.

We'll need to modify this file.

```
[...]

if [ -f /root/usr/bin/sddm ]; then
    sddm_session=plasma.desktop
    if [ -f /root/usr/share/xsessions/Lubuntu.desktop ]; then
        sddm_session=Lubuntu.desktop
    fi
    if [ -f /root/usr/share/xsessions/QLubuntu.desktop ]; then
        sddm_session=QLubuntu.desktop
    fi
    cat >>/root/etc/sddm.conf <<EOF
[Autologin]
User=$USERNAME
Session=$sddm_session
EOF
fi

log_end_msg
```

**Comment by UriHerrera** [comment] 2023-08-19 07:28
Fixed in https://github.com/Nitrux/iso-tool/commit/3eadd7ee2bebc17cad9763bc24593bc49392b0d0

It's more like a workaround from our part; it's still not fixed in casper.

**Closed by UriHerrera** 2023-08-19 07:28 UTC
Labels: upstream-bug, casper
