### ISSUE TITLE
Date&Time settings resets after windows boot

### ISSUE THREAD

**Issue by dmitriisnozik** [Nitrux/nitrux-bug-tracker#138] opened 2023-11-05 19:46 UTC
# Issue Description

**Describe the bug**

Date&Time settings resets after windows boot. I considered this as a nitrux bug and not bios issue since windows keep same time.

**Steps to reproduce the bug**

1. Boot Nitrux
2. Go to regional settings and manually set date and time
3. Reboot and boot windows
4. Reboot and boot nitrux

**Expected behavior**

Date and time remains the same as set

**Actual behavior**

Date and time settings resets

**OS version and Desktop information**

Operating System: Nitrux 3.1.0 build.311023.fx
KDE Plasma Version: 5.27.9
KDE Frameworks Version: 5.111.0
Qt Version: 5.15.11
Kernel Version: 6.4.15-2-liquorix-amd64 (64-bit)
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 5600H with Radeon Graphics
Memory: 7,2 GiB of RAM
Graphics Processor: AMD Radeon Graphics
Manufacturer: ASUSTeK COMPUTER INC.
Product Name: Vivobook_ASUSLaptop M6500QH_M6500QH
System Version: 1.0

**Comment by UriHerrera** [comment] 2023-11-05 20:56
This is a duplicate of #66

**Closed by UriHerrera** 2023-11-05 20:56 UTC
