### ISSUE TITLE
After installation the root is mounted as read-only

### ISSUE THREAD

**Issue by skyrrd** [Nitrux/nitrux-bug-tracker#40] opened 2021-12-04 23:56 UTC
**Describe the bug**
After installing the OS from 1.7.1 iso with default automatic partitioning, the roots are stuck in read-only mode, causing a wide variety of problems and rendering the OS unusable.

**To Reproduce**
1. Flash the image to a USB drive and boot from it in UEFI-mode
2. Install with default partitioning (btrfs)
3. After installation, reboot to new installed system

**Result**:
Boot hangs, alerting that rootfs is read-only
TTYs are usable as root.

**Expected behavior**
Clean Boot to Login-Screen without any errors

**Additional context**
Installing manual partitioning and ext4 as filesystem for / did work for me.

**Comment by UriHerrera** [comment] 2021-12-05 09:21
I can confirm this bug. I've tried other filesystems (XFS and EXT4); in both cases, the system installs and boots correctly. There's a problem with Calamares and BTRFS.

![VirtualBox_Nitrux_05_12_2021_03_21_14](https://user-images.githubusercontent.com/3053525/144740869-3ae3c22f-8784-4c7f-a2cb-2b4375b6c0ce.png)

**Comment by UriHerrera** [comment] 2021-12-06 23:18
### Additional Information

Below is my partition layout. I did perform a manual partitioning and chose BTRFS for the root. So there must be some problem when selecting "Erase disk" in Calamares.

![image](https://user-images.githubusercontent.com/3053525/144938126-9f8321e4-8398-46f7-b9a8-95a94d07c8f1.png)

**Comment by UriHerrera** [comment] 2021-12-13 22:19
I'll close it for now since this appears to be a problem with Calamares.

**Closed by UriHerrera** 2021-12-13 22:19 UTC
Labels: bug
