### ISSUE TITLE
Live ISO does not boot on my computer

### ISSUE THREAD

**Issue by PDXUser** [Nitrux/nitrux-bug-tracker#80] opened 2022-11-03 18:11 UTC
**Describe the bug**
When testing this distro for consideration, I get a "white screen and a black box" where the chosen OS selector is. I've tested both with Live boot from a USB drive and a virtual machine.

**To Reproduce**
1. Boot from freshly flashed ISO either live or via Virtual Machine
2. Select either option (Boot Nitrux Live or with other options)
3. Next screen for OS selection appears white screen black box where OS selection should be

**Expected behavior**
Boot into the Live boot environment.

**Screenshots**
![](https://i.imgur.com/upnM3HI.png)
![](https://i.imgur.com/t4VRZpY.png)

**Desktop (please complete the following information):**
 - OpenSuse Tumbleweed (where I flashed the ISO)
 - Firefox
 - Dell Optiplex 990 SFF PC 16GB Ram Intel video
 
**Additional context**
I tried with both ISO files available at release.

I tested using the ISO linked footer you suggested and on my main computer, (nitrux-nx-desktop-5.15-lts-kernel-20221103-amd64.iso)  It booted  fine, so I know it will work, but I will need to back up my system to be sure that I have everything moved over.   

I installed the ISO to my main computer - can you tell me how to get the Linux 6 Kernel on it?  This is essential for me.

**Comment by PDXUser** [comment] 2022-11-03 20:30
I tested with last month's ISO, it booted fine, I think I maybe misunderstood the black background to mean it was booting.  **BUT** the version from last month crashes instantly upon reaching the desktop so there is no indirect path to installing and then running a manual update via the shell.  

Further testing of this month's release 1102 release - It seems to want to immediately reboot the machine (at least in virtual machine testing).  I could see it looking for a PXE boot flash for a second or so then recurse back to the boot menu.

**Comment by UriHerrera** [comment] 2022-11-03 22:32
Let me check because the newest XanMod kernel no longer supports some hardware.

Please add more details about the hardware you're using; there are multiple SKUs for "Dell Optiplex 990 SFF ".

**Comment by PDXUser** [comment] 2022-11-04 01:27
Basically this one:
https://www.hardware-corner.net/desktop-models/Dell-OptiPlex-990-SFF/

More about it from inxi -f 

System:
  Host: desktop Kernel: 6.0.6-1-default arch: x86_64 bits: 64 Console: pty pts/1 Distro: openSUSE
    Tumbleweed 20221102
Machine:
  Type: Laptop System: Dell product: OptiPlex 990 v: 01 serial: REDACTED
  Mobo: Dell model: 0PGKWF v: A02 serial: /REDACTED/ UEFI: Dell v: A24
    date: 07/02/2018
CPU:
  Info: quad core model: Intel Core i7-2600S bits: 64 type: MT MCP cache: L2: 1024 KiB
  Speed (MHz): avg: 1603 min/max: 1600/3800 cores: 1: 1600 2: 1596 3: 1600 4: 1600 5: 1636
    6: 1600 7: 1600 8: 1596
Graphics:
  Device-1: Intel 2nd Generation Core Processor Family Integrated Graphics driver: i915 v: kernel
  Display: x11 server: X.org v: 1.21.1.4 with: Xwayland v: 22.1.4 driver: X:
    loaded: modesetting unloaded: fbdev,vesa gpu: i915 tty: 179x35 resolution: 1: 1920x1080
    2: 1920x1080
  Message: GL data unavailable in console for root.
Audio:
  Device-1: Intel 6 Series/C200 Series Family High Definition Audio driver: snd_hda_intel
  Device-2: Logitech H390 headset with microphone type: USB
    driver: hid-generic,snd-usb-audio,usbhid
  Sound Server-1: ALSA v: k6.0.6-1-default running: yes
  Sound Server-2: PipeWire v: 0.3.59 running: yes
Network:
  Device-1: Intel 82579LM Gigabit Network driver: e1000e
  IF: em1 state: up speed: 1000 Mbps duplex: full mac: REDACTED
  IF-ID-1: virbr0 state: down mac: 52:54:00:f8:5f:06
RAID:
  Hardware-1: Intel SATA Controller [RAID mode] driver: ahci
Drives:
  Local Storage: total: 232.89 GiB used: 170.43 GiB (73.2%)
  ID-1: /dev/sda vendor: Samsung model: SSD 840 EVO 250GB size: 232.89 GiB
Partition:
  ID-1: / size: 216.88 GiB used: 170.34 GiB (78.5%) fs: btrfs dev: /dev/dm-1
  ID-2: /boot/efi size: 511 MiB used: 81.6 MiB (16.0%) fs: vfat dev: /dev/sda1
  ID-3: /home size: 216.88 GiB used: 170.34 GiB (78.5%) fs: btrfs dev: /dev/dm-1
  ID-4: /opt size: 216.88 GiB used: 170.34 GiB (78.5%) fs: btrfs dev: /dev/dm-1
  ID-5: /var size: 216.88 GiB used: 170.34 GiB (78.5%) fs: btrfs dev: /dev/dm-1
Swap:
  ID-1: swap-1 type: partition size: 15.5 GiB used: 8.5 MiB (0.1%) dev: /dev/dm-0
Sensors:
  System Temperatures: cpu: 48.0 C mobo: N/A
  Fan Speeds (RPM): N/A
Info:
  Processes: 308 Uptime: 3h 3m Memory: 15.5 GiB used: 4.04 GiB (26.1%) Init: systemd Shell: Bash
  inxi: 3.3.21

**Comment by UriHerrera** [comment] 2022-11-04 09:14
I am closing this issue as OP has corroborated that the problem is with the kernel and that the test ISO works on their computer. If other users wish to add their hardware information, please do so (and don't forget to format it.)

---

@PDXUser, I noticed you've added text to your original comment. However, it's not pertinent to the issue described here; GitHub issues aren't forum threads; you're welcome to join our Telegram group or the public chat-room at Gitter if you have further questions.

**Closed by UriHerrera** 2022-11-04 09:14 UTC
Labels: upstream-bug, user-support
