### ISSUE TITLE
Time Zone Error: Unable to authenticate/execute the action 4

### ISSUE THREAD

**Issue by UnseenVoid** [Nitrux/nitrux-bug-tracker#78] opened 2022-10-02 09:22 UTC
I am getting the error:
> unable to authenticate/execute the action 4

during the set up of time automatically
the date is correct but the time is not correct

need help to fix this
![Screenshot_20221002_075101](https://user-images.githubusercontent.com/53089394/193447228-9eca1152-3e17-4a05-aca8-a4c9fe329f92.png)
![Screenshot_20221002_075158](https://user-images.githubusercontent.com/53089394/193447261-be2270bb-0e8b-4aee-8ae5-e69eb3dcb27e.png)

**Comment by UriHerrera** [comment] 2022-10-02 10:57
Duplicate of #66

**Closed by UriHerrera** 2022-10-02 10:57 UTC
