### ISSUE TITLE
Appimages not launching from Ditto Menu or Latte Dock

### ISSUE THREAD

**Issue by Sarcasmo220** [Nitrux/nitrux-bug-tracker#36] opened 2021-09-14 03:47 UTC
**Describe the bug**
Appimages are detected and found in Ditto application launcher (or if pinned, in Latte dock launcher), but will not open. Firejail configuration line in desktop file is repeated 3 times which prevents the application from launching.

**To Reproduce**
1. Download appimage from NXSC or manually from website
2. Click on Ditto application launcher, or if pinned, Latte dock application launcher
3. Click on appimage icon

**Expected behavior**
Appimage application will launch

**Desktop (please complete the following information):**
 - Nitrux 1.6.0
 - Ditto Menu
 - Latte dock
 - Wayland and X11 sessions

**Additional context**
Fix is to either launch application from file browser, launch from terminal, or remove repeated firejail lines in desktop configuration file

**Comment by UriHerrera** [comment] 2021-09-14 07:46
This is not a bug in Ditto, Latte, NXSC, or Firejail.  The program that's responsible for integrating the AppImages is [appimaged](https://github.com/AppImage/appimaged). appimaged is marked as _deprecated_ since its author created a new version called [go-appimage](https://github.com/probonopd/go-appimage).

I haven't tried this new version recently to see if it works properly now, last time I tried, it didn't work for me.

**Comment by UriHerrera** [comment] 2021-09-17 17:39
@Sarcasmo220, Can you list which AppImages you tried that didn't work?.

**Comment by Sarcasmo220** [comment] 2021-09-17 19:52
It's been every appimage I've downloaded: Poddr, Nextcloud, Kopia. It's happened regardless of whether it was from NXSC or if I download off the internet. I don't get a message, the app simply doesn't launch when I click on the icon. It seems like the firejail command is being repeated several times in the desktop file like in the image below
![Screenshot_20210917_124628](https://user-images.githubusercontent.com/68247163/133845781-fdd26b81-0403-4477-8e2b-f47d473ff779.png)

**Comment by UriHerrera** [comment] 2021-09-17 22:06
I've downloaded Poddr, Nextcloud, Brave and OBS from the software center. I can launch the apps from the software center, the app menu, and pin the launcher to Latte.

Launching the pinned launcher from Latte also works. I did get spammed with notifications regarding FUSE when opening the Nextcloud AppImage, and OBS doesn't work in a virtual machine because there's no GPU acceleration.

https://user-images.githubusercontent.com/3053525/133856014-9f0d4fca-3e26-4084-a458-25ab9f48dc88.mp4

https://user-images.githubusercontent.com/3053525/133857860-40dcbd95-4424-4c65-a121-bbde2085c472.mp4

> It's been every appimage I've downloaded: Poddr, Nextcloud, Kopia. It's happened regardless of whether it was from NXSC or if I download off the internet. I don't get a message, the app simply doesn't launch when I click on the icon. It seems like the firejail command is being repeated several times in the desktop file like in the image below
> ![Screenshot_20210917_124628](https://user-images.githubusercontent.com/68247163/133845781-fdd26b81-0403-4477-8e2b-f47d473ff779.png)

The error indeed is that the launcher created in your computer does have the command repeated numerous times. However, as you can see form the video above I opened the Nextcloud launcher (for example) and it doesn't have this problem.

Here are the other launchers that appimaged creates.

![VirtualBox_Nitrux_17_09_2021_17_04_44](https://user-images.githubusercontent.com/3053525/133858559-af3b6035-0d1a-430c-a8bd-9b777a90b884.png)
![VirtualBox_Nitrux_17_09_2021_17_04_40](https://user-images.githubusercontent.com/3053525/133858561-78b048db-5b76-47dd-b671-87da75d08843.png)
![VirtualBox_Nitrux_17_09_2021_17_04_35](https://user-images.githubusercontent.com/3053525/133858562-ef422ae9-e1d6-4104-90e6-b53bff6184a7.png)

If the problem are the launchers themselves, delete theme so they're created once again.

**Closed** 2021-12-26 07:29 UTC
Labels: unreproducible
